[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  version = "4.32.2"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200